---
- name: Provision nodes
  foreman:
       foreman_url: "{{ provisioner.foreman_url }}"
       state: present
       foreman_username: "{{ provisioner.username }}"
       foreman_password: "{{ provisioner.password }}"
       node: "{{ item.value.hostname }}"
       wait_for: "{{ distro.config.initial_boot_timeout }}"
  register: new_nodes
  retries: 4
  delay: 60
  with_dict: nodes

- local_action:
    wait_for host={{ item.value.hostname }}
             port=22 delay=10 timeout=1800
  with_dict: nodes

- name: Wait for puppet to complete
  wait_for:
         search_regex="^\s*failure\:\s*0$"
         path=/var/lib/puppet/state/last_run_summary.yaml
         state=present delay=1200 timeout=2400
  with_dict: nodes

- name: Print host openstack network type (nova/neutron)
  debug: var=provisioner.network.type

- debug: var=nodes_created
  when: job.verbosity <= verbosity.debug

- debug: var=hostvars
  when: job.verbosity <= verbosity.debug


