---
- name: Group hosts by provisioner
  hosts: local
  sudo: no
  tasks:
    - group_by: key={{ provisioner.type }}
    - group_by: key={{ provisioner.network.type }}
    - group_by: key={{ provisioner.skip }}
  tags:
    - provision

- name: Get nodes - OpenStack
  hosts: local:&openstack:!skip_provision
  sudo: no
  gather_facts: False
  roles:
    - { role: get_nodes/openstack }
  tags:
    - provision

- name: Get nodes - Rackspace
  hosts: local:&rackspace:!skip_provision
  sudo: no
  gather_facts: False
  roles:
    - { role: get_nodes/rax }
    - { role: get_nodes/add_hosts,
              nodes_created: "{{ new_nodes.results }}",
              floating_ips: [],
              network_expected: rax }
  tags:
    - provision

- name: Get nodes - Foreman
  hosts: local
  sudo: no
  gather_facts: False
  roles:
    - { role: get_nodes/foreman,
              nodes_created: "{{ new_nodes.results }}" }
              #network_expected: neutron }
  tags:
    - provision

- name: Assign floating IP and add hosts - Nova
  hosts: local:&openstack:&nova:!skip_provision
  sudo: no
  gather_facts: False
  roles:
    - { role: get_nodes/fip-nova }
    - { role: get_nodes/add_hosts,
              nodes_created: "{{ new_nodes.results }}",
              floating_ips: "{{ new_floating_ips.results }}",
              network_expected: nova }
  tags:
    - provision

- name: Assign floating IP and add hosts - Neutron
  hosts: local:&openstack:&neutron:!skip_provision
  sudo: no
  gather_facts: False
  roles:
    - { role: get_nodes/fip-neutron }
    - { role: get_nodes/add_hosts,
              nodes_created: "{{ new_nodes.results }}",
              floating_ips: "{{ new_floating_ips.results }}",
              network_expected: neutron }
  tags:
    - provision

- name: Post provision tasks
  hosts: local:!manual:!skip_provision
  sudo: no
  gather_facts: False
  roles:
    - { role: get_nodes/post }
  tags:
    - provision

- name: Set facts for hosts
  hosts: openstack_nodes:!manually-provisioned:!skip_provision
  gather_facts: False
  roles:
    - { role: set_facts }
    - { role: wait_for_hosts }
  tags:
    - provision
