---
# provison
#- include: dump_settings.yml
#determine provisioner and whether or not to skip
- include: group_by_provision.yml

- include: provision.yml
- include: group_by.yml tags=provision


- name: Wait for hosts
  hosts: foreman_nodes
  roles:
    - { role: wait_for_hosts }

- name: Add Tempest, Control, Compute Nodes
  hosts: all
  tasks:
   - add_host: name="{{ item.value.hostname }}" groups="{{ item.value.type }}"
               ansible_ssh_pass="{{ item.value.ansible_ssh_pass }}"
               admin_password="{{ item.value.admin_password }}"
     with_dict: nodes 

- include: tempest.yml

- name: SELINUX error check
  hosts: all:!localhost:!tempest
  sudo: yes
  roles:
    - { role: selinux_check }
  tags: provision

- name: clean up
  hosts: all:!localhost:!tempest
  sudo: yes
  roles:
    - { role: linux/rhsm }
